name: CI
on: [push]
runs-on: ubuntu-latest

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: make
        name: build singularity container
