name: CI
on: [push]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get install singularity-container
      - uses: actions/checkout@v2
      - run: make
        name: build singularity container
